### ISSUE TITLE
Can't reproduce fd increase bug

### ISSUE THREAD

**Issue by hitodama** [ps4dev/libps4-examples#1]
Can you try to test the claim that fd's are increasing. It does not happen on 1.75, and it would be stunning if Sony added such a bug just for 1.76 ...

https://github.com/ps4dev/libps4-examples/tree/b1fe6f230f629bd60de2c972e2d502df707f0ffb/claim/fd-increse

**Comment by psxdev** [comment]
test on 1.76
https://gist.github.com/psxdev/a9311dce870a994942d7
i don't see increment in descriptor when you close it before open new again

Which firmware is using Cturt?

**Comment by hitodama** [comment]
Hi and Thanks! :)

He should be on 1.76.

Either his descriptors increase beyond the limit because he corrupted the system prior (gained root before running the code, so the check didn't apply and then something in the fd management broke) or he triggered a weird bug in userland (which I consider less likely now).

When I first read it, I immediately thought that it seems unlikely because it is a POSIX standard behavior to take the lowest descriptor and multiple things could fail if this is not done. The elf loader for example uses the behavior.

I thought maybe it has to do with named resources (like _sceNetSocket_ when they are freed with a standard _close_ instead of a _sceNetSocketClose_) because last I heard he used defines in a patchy way (#define socket(...) sceNetSocket("socket", __VA_ARGS__)) which could provoke some random bug with named resources. But my test above checks this ... and I can't recreate anything like it.

~~Maybe I need to try using libcs "close" instead of the direct system call. I will check.~~

The only other alternative that I can come up with, is that he ran into a socket lingering issue without noticing (and that lingering counts as closed but not freed towards the counter). But that seems weird too and I have not been able to reproduce it, specifically not with a trivial socket + close loop (in which the socket state is not even connected).

**Comment by CTurt** [comment]
I've looked into this, and have just discovered that I had been receiving the described behaviour because of a bug in PS4-SDK, which has been fixed as of commit https://github.com/CTurt/PS4-SDK/commit/08073304c8f3dd041f04261f809c02875601bdb3. Basically, I wasn't closing the sockets before creating new ones, which is why I rightfully received a higher file descriptor each time. I've updated my dlclose-overflow article to fix the explanation; sorry for the inconvenience caused.

Regardless, `kern.maxfiles` is set to `0x3680` on 1.76, which should be enough for this primitive to still be useful for the majority of heap overflows.

**Comment by hitodama** [comment]
Thx, tried to make it work, but I can't really figure out all the variables (yet ...).

https://github.com/ps4dev/libps4-examples/tree/master/kernel/kexec

**Comment by segobi** [comment]
struct jail_args *uap=?;
struct prison *prison0;
prison0 = prison_find(uap->jid);

**Comment by hitodama** [comment]
Hi!

Hmm..., is that a guess or do you know how to do it :)? Since the prid from prison_find is an int prison_find(0) would be the simpler way, no? But from what I have seen, prison0 is not listed in pr_list - so prison_find shouldn't work?

The best way I can imagine to get the address, is to read a fixed offset in a function (say jailed + xyz) but I currently don't have an address to such a function.

My bigger problem for now is that the whole thing does not want to run & print etc :)

Regardless, any comments are welcome :)

**Comment by CTurt** [comment]
You are approaching this incorrectly.

As I explained in my PS4 kernel exploitation guide: your immediate goal should be to confirm that you first have kernel code execution by calling `sys_sendto` and dumping the kernel. You can find the address of `sys_sendto` through the `kern.proc.kstack` node of `sysctl` (there are other ways to leak kernel addresses too, but this is the easiest).

Once you've dumped the kernel, you can load it into a debugger, and easily find addresses of variables like `prison0` to build payloads which perform privilege escalation, sandbox escape, and everything else that I explained in my article. Since there is no kernel ASLR, you don't need to fetch these values dynamically.

With that said, I took a brief look at your kernel exploit attempt, and it seems like you misunderstood some things. I recommend exploiting the bug on FreeBSD first, as explained in the article, and then porting to PS4.

**Comment by hitodama** [comment]
Actually, I don't think that's true.

Towards point 1) I try to do exactly that. I try to send an arbitrary message to stdout and a socket. I am not sure what td is (i am guessing gs:0 - trying freebsd wouldn't help me there) but that's all I am trying. The whole privileged escalation is absolutely just a gimmick in the code and basically not critical. So I go even lower then "dump the kernel" and just try to print (in this case some bytes or arbitrary kernel memory), which is fine as an approach.

Towards 2) Could you point out one explicit thing about the core exploit setup that I am doing wrong? Because I actually think I may have an assumption wrong, but over all this is the correct way to do the exploit. Though I may eventually get around to implement a kernel module on a freebsd and set it up properly, I am not sure it is needed and I am not in much of a hurry.

EDIT: Ah, see i found my (probably primary) mistake. It's all those structs and defines (lists) in FreeBSD that made me miss a layer of abstractions (assume a wrong type layout). I am somewhat confident that it will work after fixing that ~~(later today)~~ (no time).
